import pexpect
import time
child = pexpect.spawn('bash')
child.expect(r'\$')
child.sendline('ssh 192.168.43.126')
child.expect(r'\$')
child.sendline('Dreams97')
child.expect(r'\$')
child.sendline('sudo killall /usr/bin/omxplayer.bin')
child.expect(r'\$')
child.sendline('nohup omxplayer /home/pi/21.mp4 --aspect-mode stretch --no-osd')
time.sleep(1)
child2 = pexpect.spawn('bash')
child2.expect(r'\$')
child2.sendline('sudo killall /usr/bin/omxplayer.bin')
child2.expect(r'\$')
child2.sendline('nohup omxplayer 12.mp4 --aspect-mode stretch --no-osd')
time.sleep(4)
child.expect(r'\$')
child.sendline('nohup omxplayer 1.mp4 --loop --aspect-mode stretch --no-osd')
child2.expect(r'\$')
child2.sendline('nohup omxplayer 5.mp4 --loop --aspect-mode stretch --no-osd')
